db_file: mtg_tournament.db
log_db_file: mtg_tournament_logs.db
admin_email: admin@example.com
admin_pass: admin123
flask_secret: dev-secret-change-me
password_seed: dev-password-seed-change-me
#flask_ip: 10.147.17.136
flask_ip: 192.168.1.85
flask_port: 5000
