"""League scoring and rating algorithms.

The functions in this module deliberately have no Flask/SQLAlchemy dependency so
the rules can be tested independently from the web application.
"""

import math


def select_results(results, system, percentage, field_maximum=0):
    """Return the results which count for a best-X scoring system."""
    ordered = sorted(
        results,
        key=lambda result: (result.points or 0, result.wins or 0, -(result.losses or 0)),
        reverse=True,
    )
    if system == 'colley':
        return ordered
    if system == 'field_best':
        count = min(len(ordered), math.ceil(field_maximum * percentage / 100))
    else:
        count = math.ceil(len(ordered) * percentage / 100) if ordered else 0
    return ordered[:count]


def colley_ratings(player_ids, games):
    """Solve the Colley matrix for ``(player1, player2, score1)`` games."""
    ids = list(player_ids)
    size = len(ids)
    if not size:
        return {}
    positions = {player_id: index for index, player_id in enumerate(ids)}
    matrix = [[0.0] * size for _ in range(size)]
    vector = [1.0] * size
    wins = [0] * size
    losses = [0] * size
    for player1, player2, score1 in games:
        if player1 not in positions or player2 not in positions:
            continue
        first, second = positions[player1], positions[player2]
        matrix[first][second] -= 1
        matrix[second][first] -= 1
        matrix[first][first] += 1
        matrix[second][second] += 1
        if score1 > 0.5:
            wins[first] += 1
            losses[second] += 1
        elif score1 < 0.5:
            wins[second] += 1
            losses[first] += 1
    for index in range(size):
        matrix[index][index] += 2
        vector[index] += (wins[index] - losses[index]) / 2

    # Gauss-Jordan elimination is sufficient for the small, positive-definite
    # matrices generated by a league.
    augmented = [row[:] + [vector[index]] for index, row in enumerate(matrix)]
    for column in range(size):
        pivot = max(range(column, size), key=lambda row: abs(augmented[row][column]))
        augmented[column], augmented[pivot] = augmented[pivot], augmented[column]
        divisor = augmented[column][column]
        for cell in range(column, size + 1):
            augmented[column][cell] /= divisor
        for row in range(size):
            if row == column:
                continue
            factor = augmented[row][column]
            for cell in range(column, size + 1):
                augmented[row][cell] -= factor * augmented[column][cell]
    return {player_id: augmented[index][-1] for index, player_id in enumerate(ids)}


def glicko_ratings(player_ids, games):
    """Calculate Glicko-1 ratings and rating deviations in chronological order."""
    q = math.log(10) / 400
    ratings = {player_id: [1500.0, 350.0] for player_id in player_ids}
    for player1, player2, score1 in games:
        if player1 not in ratings or player2 not in ratings:
            continue
        rating1, deviation1 = ratings[player1]
        rating2, deviation2 = ratings[player2]

        def update(rating, deviation, opponent_rating, opponent_deviation, score):
            g = 1 / math.sqrt(1 + (3 * q * q * opponent_deviation * opponent_deviation) / (math.pi * math.pi))
            expected = 1 / (1 + 10 ** (-g * (rating - opponent_rating) / 400))
            variance = 1 / (q * q * g * g * expected * (1 - expected))
            precision = 1 / (deviation * deviation) + 1 / variance
            new_deviation = math.sqrt(1 / precision)
            new_rating = rating + (q / precision) * g * (score - expected)
            return [new_rating, new_deviation]

        # Both updates use the ratings at the start of the game.
        ratings[player1] = update(rating1, deviation1, rating2, deviation2, score1)
        ratings[player2] = update(rating2, deviation2, rating1, deviation1, 1 - score1)
    return ratings
